---
version: "3"

tasks:
  re-encrypt:
    desc: Rotate all sops secrets
    silent: true
    dir: "{{.USER_WORKING_DIR}}"
    vars:
      SECRET_FILES:
        sh: find . -type f -name '*.sops.yaml' ! -name ".sops.yaml"
    cmds:
      - for: { var: SECRET_FILES }
        cmd: |
          echo "Rotating {{ .ITEM }}"
          sops --rotate --in-place "{{ .ITEM }}"
