#!/usr/bin/env bash
# Generate PR body for package updates

PKG="$1"
OWNER="$2"
REPO="$3"
OLD_VERSION="$4"
NEW_VERSION="$5"
CHANGELOG="$6"

cat <<EOF
## 📦 Package Update

| | |
|---|---|
| **Package** | \`${PKG}\` |
| **Source** | [\`${OWNER}/${REPO}\`](https://github.com/${OWNER}/${REPO}) |
| **Version** | \`${OLD_VERSION}\` → \`${NEW_VERSION}\` |

### ✅ Verification

- [x] Hashes updated automatically
- [ ] Ready for review

---

<details>
<summary>📝 Release Notes & Changelog</summary>

${CHANGELOG}

</details>

---

<sub>🤖 This PR was automatically generated by [update-pkgs.yaml](.github/workflows/update-pkgs.yaml)</sub>
EOF
