---
keys:
  - &user_krezh age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
  - &user_krezh_yubikey age1yubikey1qt83fjzawhcmxn7duntq30u67etg2t2y0fmu6d9z3cgh2q7ff7dn5xrpzdk

creation_rules:
  - path_regex: ^[^.].*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
          #- *user_krezh_yubikey
