---
keys:
  - &user_krezh age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
  - &user_krezh_yubikey age1yubikey1qt83fjzawhcmxn7duntq30u67etg2t2y0fmu6d9z3cgh2q7ff7dn5xrpzdk
  - &system_thor age1la8yyuay3f6jzkfggmqsl5dekfe56lk0w83z8x93lyf7k6lf9asskczezw
  - &buildbot age1le7ztz9e9z7uk5lgt75tq4vl2gpxx8la93cl2qu4fgsuf00cdgrs3pe85c

creation_rules:
  - path_regex: hosts/buildbot-master/secrets\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
          - *user_krezh_yubikey
          - *buildbot
  - path_regex: hosts/buildbot-worker/secrets\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
          - *user_krezh_yubikey
          - *buildbot
  - path_regex: ^[^.].*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
          - *user_krezh_yubikey
          - *system_thor
