---
keys:
  - &user_krezh age1el5jq43hnhq8uzyfruretlrxk0ch8xvykdzu94cfsu5tyywwga3qy3f46h
  - &user_krezh_ykey age1yubikey1qdwwcxxstqw9kwgw37xuf3lc3ua2ql7cphgwnkv6udm9zavj0ndgug3ades # Requires https://github.com/getsops/sops/pull/1335

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_krezh
