---
version: "3"

vars:
  PKGS:
    sh: ls -1 pkgs/bin -I "default.nix"
  HOST: $HOSTNAME

tasks:
  update-packages:
    desc: Update nix packages
    silent: true
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nix-update
        msg: "nix-update not found"
    cmds:
      - for: { var: PKGS }
        cmd: nix-update --flake --commit "{{ .ITEM }}"

  apply:
    desc: Build and apply nix configuration
    silent: true
    requires:
      vars:
        - HOST
    cmds:
      - task: build
        vars:
          HOST: "{{ .HOST }}"
      - task: .prompt_to_continue
      - sudo nixos-rebuild switch --flake "{{.ROOT_DIR}}/#{{.HOST}}"
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  build:
    desc: Build nix configuration
    silent: true
    requires:
      vars:
        - HOST
    cmds:
      - nixos-rebuild build --flake "{{.ROOT_DIR}}/#{{.HOST}}"
      - nvd diff /run/current-system result
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
