---
version: "3"

vars:
  host: $HOSTNAME

tasks:
  update-packages:
    desc: Update nix packages
    cmds:
      - nix-update --flake talosctl
    preconditions:
      - sh: which nix
        msg: "nix not found"
