[package]
name = "hypr-slurp"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
smithay-client-toolkit = { version = "0.20", default-features = false, features = ["calloop", "xkbcommon"] }
cairo-rs = { version = "0.21", features = ["png"] }
image = "0.25"
memmap2 = "0.9"
nix = { version = "0.29", features = ["fs", "mman"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
calloop = "0.14"
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3              # Maximum optimization
lto = "fat"                # Full link-time optimization across all crates
codegen-units = 1          # Better optimization at cost of compile time
strip = true               # Remove debug symbols
panic = "abort"            # Smaller binary, faster panic handling
overflow-checks = false    # Disable integer overflow checks in release
