---
name: "Post Build Success Comment"
description: "Posts build success info to PR comments"
author: "krezh"

inputs:
  build-type:
    description: "Type of build (host or package)"
    required: true
  build-name:
    description: "Name of package or host"
    required: true
  flake-target:
    description: "Flake target that succeeded"
    required: true
  build-duration:
    description: "Build duration in seconds"
    required: true
  build-size:
    description: "Build closure size"
    required: false
    default: "Unknown"
  runner:
    description: "Runner type"
    required: true
  pr-number:
    description: "PR number"
    required: true

runs:
  using: "composite"
  steps:
    - name: Comment build success on PR
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      with:
        header: "${{ inputs.build-type == 'host' && 'Host' || 'Package' }} Build Success: ${{ inputs.build-name }}"
        message: |
          ## ✅ ${{ inputs.build-type == 'host' && 'Host' || 'Package' }} Build Success: `${{ inputs.build-name }}`

          **Flake Target:** `${{ inputs.flake-target }}`
          **Runner:** `${{ inputs.runner }}`
          **Build Time:** ${{ inputs.build-duration }}s
          **Closure Size:** ${{ inputs.build-size }}

          ### Reproduce Locally
          ```bash
          nix build github:${{ github.repository }}/pull/${{ inputs.pr-number }}/head#${{ inputs.flake-target }}
          ```

          ---
          <sub>🤖 [View full logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})</sub>
