---
name: "Post Build Success Comment"
description: "Posts build success information to PR comments"
author: "krezh"

inputs:
  build-type:
    description: "Type of build (package, system, or iso)"
    required: true
  build-name:
    description: "Name of package or host"
    required: true
  flake-target:
    description: "Flake build target"
    required: true
  build-size:
    description: "Build size in human readable format"
    required: false
    default: "Unknown"
  build-duration:
    description: "Build duration in seconds"
    required: false
    default: "0"
  result-path:
    description: "Nix store result path"
    required: false
    default: ""
  runner:
    description: "Runner type"
    required: false
    default: ""
  pr-number:
    description: "PR number"
    required: true

runs:
  using: "composite"
  steps:
    - name: Format build duration
      id: format-duration
      shell: bash
      run: |
        duration_seconds="${{ inputs.build-duration }}"
        if [ -z "$duration_seconds" ] || [ "$duration_seconds" = "0" ]; then
          echo "formatted=0s" >> $GITHUB_OUTPUT
        elif [ "$duration_seconds" -ge 3600 ]; then
          hours=$((duration_seconds / 3600))
          minutes=$(((duration_seconds % 3600) / 60))
          seconds=$((duration_seconds % 60))
          echo "formatted=${hours}h${minutes}m${seconds}s" >> $GITHUB_OUTPUT
        elif [ "$duration_seconds" -ge 60 ]; then
          minutes=$((duration_seconds / 60))
          seconds=$((duration_seconds % 60))
          echo "formatted=${minutes}m${seconds}s" >> $GITHUB_OUTPUT
        else
          echo "formatted=${duration_seconds}s" >> $GITHUB_OUTPUT
        fi

    - name: Comment build success on PR
      uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
      with:
        header: "${{ inputs.build-type == 'package' && 'Package' || 'System' }} Build: ${{ inputs.build-name }}"
        message: |
          ## ✅ ${{ inputs.build-type == 'package' && 'Package' || 'System' }} Build Successful: `${{ inputs.build-name }}`

          | Property | Value |
          |----------|-------|
          | **${{ inputs.build-type == 'package' && 'Package' || 'Host' }}** | `${{ inputs.build-name }}` |${{ inputs.runner && format('
          | **Runner** | `{0}` |', inputs.runner) || '' }}${{ inputs.build-size && format('
          | **Build Size** | `{0}` |', inputs.build-size) || '' }}
          | **Duration** | ${{ steps.format-duration.outputs.formatted }} |${{ inputs.result-path && format('
          | **Store Path** | `{0}` |', inputs.result-path) || '' }}

          **Flake Target:** `${{ inputs.flake-target }}`

          ---
          <sub>🤖 [View full logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})</sub>
