name: Setup Nix with Caching
description: Install Nix and configure Attic cache
inputs:
  attic-endpoint:
    description: Attic cache endpoint
    required: false
  attic-cache:
    description: Attic cache name
    required: false
  attic-token:
    description: Attic authentication token
    required: false
  skip-cache:
    description: Skip cache setup (for forks/external PRs)
    required: false
    default: "false"
  remote-builders:
    description: Remote Nix builders configuration (comma-separated)
    required: false
    default: ""
  remote-builders-ssh-key:
    description: SSH private key for remote builders
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4
      with:
        install_options: --no-daemon
        extra_nix_config: |
          accept-flake-config = true
          always-allow-substitutes = true
          builders-use-substitutes = true

    - name: Setup SSH Key for Remote Builders
      if: inputs.remote-builders != '' && inputs.remote-builders-ssh-key != ''
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.remote-builders-ssh-key }}" > ~/.ssh/nix-builder-key
        chmod 600 ~/.ssh/nix-builder-key
        cat >> ~/.ssh/config <<EOF
        Host *
          StrictHostKeyChecking accept-new
          IdentityFile ~/.ssh/nix-builder-key
        EOF
        chmod 600 ~/.ssh/config
        echo "SSH key configured for remote builders"

    - name: Configure Remote Builders
      if: inputs.remote-builders != ''
      shell: bash
      run: |
        mkdir -p ~/.config/nix
        echo "builders = ${{ inputs.remote-builders }}" >> ~/.config/nix/nix.conf
        echo "max-jobs = 0" >> ~/.config/nix/nix.conf
        echo "Remote builders configured:"
        cat ~/.config/nix/nix.conf

    - name: Setup Attic
      if: inputs.skip-cache != 'true'
      uses: ryanccn/attic-action@7fbafba3978e86e585cb68a82c08b30f3672b62d # v0.4.0
      with:
        endpoint: ${{ inputs.attic-endpoint }}
        cache: ${{ inputs.attic-cache }}
        token: ${{ inputs.attic-token }}
