name: Setup Nix with Caching
description: Install Nix and configure cache
inputs:
  cachix-cache:
    description: Cachix cache name
    required: false
  cachix-token:
    description: Cachix authentication token
    required: false
  attic-endpoint:
    description: Attic cache endpoint
    required: false
  attic-cache:
    description: Attic cache name
    required: false
  attic-token:
    description: Attic authentication token
    required: false
  skip-cache:
    description: Skip cache setup
    required: false
    default: "false"
  skip-push:
    description: Skip cache push
    required: false
    default: "false"
  use-remote-builders:
    description: Enable remote builders
    required: false
    default: "false"
  remote-builders-ssh-key:
    description: SSH private key for remote builders
    required: false
    default: ""
  nothing-but-nix:
    description: Enable nothing-but-nix mode (uses /nix/build as build directory)
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Nothing But Nix
      if: inputs.nothing-but-nix == 'true'
      uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
      with:
        hatchet-protocol: cleave
        nix-permission-edict: true

    - name: Setup SSH Key for Remote Builders
      if: inputs.use-remote-builders == 'true' && inputs.remote-builders-ssh-key != ''
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.remote-builders-ssh-key }}" > ~/.ssh/nix-builder-key
        chmod 600 ~/.ssh/nix-builder-key
        cat >> ~/.ssh/config <<EOF
        Host *
          StrictHostKeyChecking accept-new
          IdentityFile ~/.ssh/nix-builder-key
        EOF
        chmod 600 ~/.ssh/config

    - name: Install Nix (with remote builders)
      if: inputs.use-remote-builders == 'true'
      uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      with:
        install_options: --no-daemon
        extra_nix_config: |
          accept-flake-config = true
          always-allow-substitutes = true
          builders-use-substitutes = true
          max-jobs = 0
          builders = @${{ github.workspace }}/.github/nix-builders.conf
          ${{ inputs.nothing-but-nix == 'true' && 'build-dir = /nix/build' || '' }}

    - name: Install Nix (local)
      if: inputs.use-remote-builders != 'true'
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      with:
        nix_conf: |
          accept-flake-config = true
          always-allow-substitutes = true
          ${{ inputs.nothing-but-nix == 'true' && 'build-dir = /nix/build' || '' }}

    - name: Setup Cachix
      if: inputs.skip-cache != 'true' && inputs.cachix-cache != '' && inputs.cachix-token != ''
      uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: ${{ inputs.cachix-cache }}
        authToken: ${{ inputs.cachix-token }}
        skipPush: ${{ inputs.skip-push }}

    - name: Setup Attic
      if: inputs.skip-cache != 'true' && inputs.attic-endpoint != '' && inputs.attic-cache != '' && inputs.attic-token != ''
      uses: ryanccn/attic-action@1887fd507f03327c96c64cca30118c96eb17fdad # v0.4.1
      with:
        endpoint: ${{ inputs.attic-endpoint }}
        cache: ${{ inputs.attic-cache }}
        token: ${{ inputs.attic-token }}
