name: Setup Nix with Caching
description: Install Nix and configure Cachix cache
inputs:
  cachix-cache:
    description: Cachix cache name
    required: false
  cachix-token:
    description: Cachix authentication token
    required: false
  skip-cache:
    description: Skip cache setup
    required: false
    default: "false"
  skip-push:
    description: Skip cache push
    required: false
    default: "false"
  use-remote-builders:
    description: Enable remote builders
    required: false
    default: "false"
  remote-builders-ssh-key:
    description: SSH private key for remote builders
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Setup SSH Key for Remote Builders
      if: inputs.use-remote-builders == 'true' && inputs.remote-builders-ssh-key != ''
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.remote-builders-ssh-key }}" > ~/.ssh/nix-builder-key
        chmod 600 ~/.ssh/nix-builder-key
        cat >> ~/.ssh/config <<EOF
        Host *
          StrictHostKeyChecking accept-new
          IdentityFile ~/.ssh/nix-builder-key
        EOF
        chmod 600 ~/.ssh/config

    - name: Install Nix (with remote builders)
      if: inputs.use-remote-builders == 'true'
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      with:
        install_options: --no-daemon
        extra_nix_config: |
          accept-flake-config = true
          always-allow-substitutes = true
          builders-use-substitutes = true
          max-jobs = 0
          builders = @${{ github.workspace }}/.github/nix-builders.conf
          build-dir = /nix/build

    - name: Install Nix (local)
      if: inputs.use-remote-builders != 'true'
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      with:
        nix_conf: |
          accept-flake-config = true
          always-allow-substitutes = true
          build-dir = /nix/build

    - name: Setup Cachix
      if: inputs.skip-cache != 'true'
      uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: ${{ inputs.cachix-cache }}
        authToken: ${{ inputs.cachix-token }}
        skipPush: ${{ inputs.skip-push }}
